set(_CATKIN_CURRENT_PACKAGE "abridge")
set(abridge_VERSION "0.2.0")
set(abridge_MAINTAINER "NASA Swarmathon <swarmathon@cs.unm.edu>")
set(abridge_PACKAGE_FORMAT "1")
set(abridge_BUILD_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "nav_msgs")
set(abridge_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "nav_msgs")
set(abridge_BUILDTOOL_DEPENDS "catkin")
set(abridge_BUILDTOOL_EXPORT_DEPENDS )
set(abridge_EXEC_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "nav_msgs")
set(abridge_RUN_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "nav_msgs")
set(abridge_TEST_DEPENDS )
set(abridge_DOC_DEPENDS )
set(abridge_DEPRECATED "")