/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/kstolleis/rover_cloud_workspace/src/rover_cloud_world_state/srv/updateMap.srv
 *
 */


#ifndef ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAP_H
#define ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAP_H

#include <ros/service_traits.h>


#include <rover_cloud_world_state/updateMapRequest.h>
#include <rover_cloud_world_state/updateMapResponse.h>


namespace rover_cloud_world_state
{

struct updateMap
{

typedef updateMapRequest Request;
typedef updateMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct updateMap
} // namespace rover_cloud_world_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rover_cloud_world_state::updateMap > {
  static const char* value()
  {
    return "372335294753d02c4b4770f631b22fd0";
  }

  static const char* value(const ::rover_cloud_world_state::updateMap&) { return value(); }
};

template<>
struct DataType< ::rover_cloud_world_state::updateMap > {
  static const char* value()
  {
    return "rover_cloud_world_state/updateMap";
  }

  static const char* value(const ::rover_cloud_world_state::updateMap&) { return value(); }
};


// service_traits::MD5Sum< ::rover_cloud_world_state::updateMapRequest> should match 
// service_traits::MD5Sum< ::rover_cloud_world_state::updateMap > 
template<>
struct MD5Sum< ::rover_cloud_world_state::updateMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rover_cloud_world_state::updateMap >::value();
  }
  static const char* value(const ::rover_cloud_world_state::updateMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_cloud_world_state::updateMapRequest> should match 
// service_traits::DataType< ::rover_cloud_world_state::updateMap > 
template<>
struct DataType< ::rover_cloud_world_state::updateMapRequest>
{
  static const char* value()
  {
    return DataType< ::rover_cloud_world_state::updateMap >::value();
  }
  static const char* value(const ::rover_cloud_world_state::updateMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rover_cloud_world_state::updateMapResponse> should match 
// service_traits::MD5Sum< ::rover_cloud_world_state::updateMap > 
template<>
struct MD5Sum< ::rover_cloud_world_state::updateMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rover_cloud_world_state::updateMap >::value();
  }
  static const char* value(const ::rover_cloud_world_state::updateMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_cloud_world_state::updateMapResponse> should match 
// service_traits::DataType< ::rover_cloud_world_state::updateMap > 
template<>
struct DataType< ::rover_cloud_world_state::updateMapResponse>
{
  static const char* value()
  {
    return DataType< ::rover_cloud_world_state::updateMap >::value();
  }
  static const char* value(const ::rover_cloud_world_state::updateMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAP_H
