/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/kstolleis/rover_cloud_workspace/src/rover_cloud_world_state/srv/updateMap.srv
 *
 */


#ifndef ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAPRESPONSE_H
#define ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_cloud_world_state
{
template <class ContainerAllocator>
struct updateMapResponse_
{
  typedef updateMapResponse_<ContainerAllocator> Type;

  updateMapResponse_()
    : mapUpdated(false)  {
    }
  updateMapResponse_(const ContainerAllocator& _alloc)
    : mapUpdated(false)  {
    }



   typedef uint8_t _mapUpdated_type;
  _mapUpdated_type mapUpdated;




  typedef boost::shared_ptr< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct updateMapResponse_

typedef ::rover_cloud_world_state::updateMapResponse_<std::allocator<void> > updateMapResponse;

typedef boost::shared_ptr< ::rover_cloud_world_state::updateMapResponse > updateMapResponsePtr;
typedef boost::shared_ptr< ::rover_cloud_world_state::updateMapResponse const> updateMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_cloud_world_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rover_cloud_world_state': ['/home/kstolleis/rover_cloud_workspace/src/rover_cloud_world_state/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3859fc1129f2870f73f28496c74ce4a";
  }

  static const char* value(const ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3859fc1129f2870ULL;
  static const uint64_t static_value2 = 0xf73f28496c74ce4aULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_cloud_world_state/updateMapResponse";
  }

  static const char* value(const ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool mapUpdated\n\
\n\
";
  }

  static const char* value(const ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapUpdated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct updateMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_cloud_world_state::updateMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "mapUpdated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mapUpdated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_CLOUD_WORLD_STATE_MESSAGE_UPDATEMAPRESPONSE_H
