set(_CATKIN_CURRENT_PACKAGE "diagnostics")
set(diagnostics_VERSION "0.0.0")
set(diagnostics_MAINTAINER "NASA Swarmathon <swarmathon@cs.unm.edu>")
set(diagnostics_PACKAGE_FORMAT "1")
set(diagnostics_BUILD_DEPENDS "roscpp" "std_msgs")
set(diagnostics_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(diagnostics_BUILDTOOL_DEPENDS "catkin")
set(diagnostics_BUILDTOOL_EXPORT_DEPENDS )
set(diagnostics_EXEC_DEPENDS "roscpp" "std_msgs")
set(diagnostics_RUN_DEPENDS "roscpp" "std_msgs")
set(diagnostics_TEST_DEPENDS )
set(diagnostics_DOC_DEPENDS )
set(diagnostics_DEPRECATED "")