/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gmontague/catkin_ws/src/april_tags/msg/imgDataArray.msg
 *
 */


#ifndef APRIL_TAGS_MESSAGE_IMGDATAARRAY_H
#define APRIL_TAGS_MESSAGE_IMGDATAARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace april_tags
{
template <class ContainerAllocator>
struct imgDataArray_
{
  typedef imgDataArray_<ContainerAllocator> Type;

  imgDataArray_()
    : images()  {
    }
  imgDataArray_(const ContainerAllocator& _alloc)
    : images(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _images_type;
  _images_type images;




  typedef boost::shared_ptr< ::april_tags::imgDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::april_tags::imgDataArray_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct imgDataArray_

typedef ::april_tags::imgDataArray_<std::allocator<void> > imgDataArray;

typedef boost::shared_ptr< ::april_tags::imgDataArray > imgDataArrayPtr;
typedef boost::shared_ptr< ::april_tags::imgDataArray const> imgDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::april_tags::imgDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::april_tags::imgDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace april_tags

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'april_tags': ['/home/gmontague/catkin_ws/src/april_tags/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::april_tags::imgDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::april_tags::imgDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::april_tags::imgDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::april_tags::imgDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tags::imgDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::april_tags::imgDataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::april_tags::imgDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34b77a05c9aa29183039a20e6d608d6d";
  }

  static const char* value(const ::april_tags::imgDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34b77a05c9aa2918ULL;
  static const uint64_t static_value2 = 0x3039a20e6d608d6dULL;
};

template<class ContainerAllocator>
struct DataType< ::april_tags::imgDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "april_tags/imgDataArray";
  }

  static const char* value(const ::april_tags::imgDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::april_tags::imgDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] images\n\
";
  }

  static const char* value(const ::april_tags::imgDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::april_tags::imgDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.images);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct imgDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::april_tags::imgDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::april_tags::imgDataArray_<ContainerAllocator>& v)
  {
    s << indent << "images[]" << std::endl;
    for (size_t i = 0; i < v.images.size(); ++i)
    {
      s << indent << "  images[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.images[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRIL_TAGS_MESSAGE_IMGDATAARRAY_H
