/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gmontague/rover_onboard_workspace/src/rover_onboard_target_detection/msg/Num.msg
 *
 */


#ifndef ROVER_ONBOARD_TARGET_DETECTION_MESSAGE_NUM_H
#define ROVER_ONBOARD_TARGET_DETECTION_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_onboard_target_detection
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : numDetections(0)
    , idA(0)
    , idB(0)
    , idC(0)
    , idD(0)
    , idE(0)
    , idF(0)
    , idG(0)
    , idH(0)
    , idI(0)
    , idJ(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : numDetections(0)
    , idA(0)
    , idB(0)
    , idC(0)
    , idD(0)
    , idE(0)
    , idF(0)
    , idG(0)
    , idH(0)
    , idI(0)
    , idJ(0)  {
    }



   typedef int32_t _numDetections_type;
  _numDetections_type numDetections;

   typedef int32_t _idA_type;
  _idA_type idA;

   typedef int32_t _idB_type;
  _idB_type idB;

   typedef int32_t _idC_type;
  _idC_type idC;

   typedef int32_t _idD_type;
  _idD_type idD;

   typedef int32_t _idE_type;
  _idE_type idE;

   typedef int32_t _idF_type;
  _idF_type idF;

   typedef int32_t _idG_type;
  _idG_type idG;

   typedef int32_t _idH_type;
  _idH_type idH;

   typedef int32_t _idI_type;
  _idI_type idI;

   typedef int32_t _idJ_type;
  _idJ_type idJ;




  typedef boost::shared_ptr< ::rover_onboard_target_detection::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_onboard_target_detection::Num_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Num_

typedef ::rover_onboard_target_detection::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::rover_onboard_target_detection::Num > NumPtr;
typedef boost::shared_ptr< ::rover_onboard_target_detection::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_onboard_target_detection::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_onboard_target_detection::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_onboard_target_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'rover_onboard_target_detection': ['/home/gmontague/rover_onboard_workspace/src/rover_onboard_target_detection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_onboard_target_detection::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_onboard_target_detection::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_onboard_target_detection::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6be9581da6d5f87c59e05cdd5120cc52";
  }

  static const char* value(const ::rover_onboard_target_detection::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6be9581da6d5f87cULL;
  static const uint64_t static_value2 = 0x59e05cdd5120cc52ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_onboard_target_detection/Num";
  }

  static const char* value(const ::rover_onboard_target_detection::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 numDetections\n\
int32 idA\n\
int32 idB\n\
int32 idC\n\
int32 idD\n\
int32 idE\n\
int32 idF\n\
int32 idG\n\
int32 idH\n\
int32 idI\n\
int32 idJ\n\
";
  }

  static const char* value(const ::rover_onboard_target_detection::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numDetections);
      stream.next(m.idA);
      stream.next(m.idB);
      stream.next(m.idC);
      stream.next(m.idD);
      stream.next(m.idE);
      stream.next(m.idF);
      stream.next(m.idG);
      stream.next(m.idH);
      stream.next(m.idI);
      stream.next(m.idJ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_onboard_target_detection::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_onboard_target_detection::Num_<ContainerAllocator>& v)
  {
    s << indent << "numDetections: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numDetections);
    s << indent << "idA: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idA);
    s << indent << "idB: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idB);
    s << indent << "idC: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idC);
    s << indent << "idD: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idD);
    s << indent << "idE: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idE);
    s << indent << "idF: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idF);
    s << indent << "idG: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idG);
    s << indent << "idH: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idH);
    s << indent << "idI: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idI);
    s << indent << "idJ: ";
    Printer<int32_t>::stream(s, indent + "  ", v.idJ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_ONBOARD_TARGET_DETECTION_MESSAGE_NUM_H
